"""empty message

Revision ID: e3124e236672
Revises: 503705f86425
Create Date: 2022-12-25 15:26:23.702400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3124e236672'
down_revision = '503705f86425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.DateTime(), nullable=True))
        batch_op.drop_column('completion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
